### ISSUE TITLE
GetModuleHandleExW...

### ISSUE THREAD

**Issue by 6b3478** [Octoberfest7/Mutants_Sessions_Self-Deletion#1]
..Not necessery, cos u can add:
```EXTERN_C IMAGE_DOS_HEADER __ImageBase;``` to begin of your source(after windows.h).

After that you can simle resolve image_path by GetModuleFileNameW:
```
   WCHAR wcPath[MAX_PATH + 1];
   _bzero(wcPath, sizeof(wcPath));
   GetModuleFileNameW((HINSTANCE)&__ImageBase, wcPath, _countof(wcPath));
```

**Comment by Octoberfest7** [comment]
Thanks for the alternate solution. Seeing as the provided one works and this is simply research, I am closing this issue.
